name: osc commit
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: init config
        env:
          OSCRC: ${{secrets.OSCRC}}
        run: |
          sudo apt-get install -y osc
          mkdir -p ~/.config/osc/
          echo "$OSCRC" > ~/.config/osc/oscrc

      - uses: actions/checkout@v3
      - name: update lib
        run: cd lib && bash "../.github/workflows/commit.bash"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auot osc commit"
          commit_user_name: myml
          commit_user_email: wurongjie@deepin.org
