name: osc commit
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: init config
        env:
            OSCRC: ${{secrets.OSCRC}}
        run: |
          mkdir -p ~/.config/osc/
          echo "$OSCRC" > ~/.config/osc/oscrc
          apt-get install -y osc
      - uses: actions/checkout@v3
      - name: update lib
        run: |
          cd lib
          osc up
          osc add */*
          osc commit -m "auto commit"
